- name: stop axia service
  systemd:
    name: axia.service
    state: stopped

- name: purge chain
  shell: |
    set -o pipefail
    /usr/local/bin/axia purge-chain -y
  become: yes
  become_user: axia
  args:
    executable: /bin/bash
  changed_when: False

- name: start axia service
  systemd:
    name: axia.service
    state: started
